//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.WaterUsage.Customers
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountService
    {
        public int account_number { get; set; }
        public short occupant_code { get; set; }
        public string utility_type { get; set; }
        public string bill_code { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string category_code { get; set; }
    }
}
