//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.WaterUsage.Customers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int account_number { get; set; }
        public short occupant_code { get; set; }
        public Nullable<int> debtor_number { get; set; }
        public Nullable<decimal> street_number { get; set; }
        public string street { get; set; }
        public string unit { get; set; }
        public string region { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string zip { get; set; }
    }
}
