//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.WaterUsage.Customers.EF
{
    using System;
    using System.Collections.Generic;
    
    internal partial class UsageRecord
    {
        public int account_number { get; set; }
        public short occupant_code { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<decimal> net { get; set; }
        public Nullable<System.DateTime> prorate_from { get; set; }
        public Nullable<System.DateTime> prorate_to { get; set; }
        public Nullable<decimal> usage_billed { get; set; }
        public int batch_number { get; set; }
        public string utility_type { get; set; }
        public string bill_code { get; set; }
        public short canrev { get; set; }
    }
}
